/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import util.MessageSaves;
import util.ReceiverClient;
import util.Sender;
import util.User;

/**
 *
 * @author Larry Finol y Alejandro
 */
public class Home extends javax.swing.JFrame implements Serializable {

    private String userName, server, chat;
    private Sender sender;
    private ReceiverClient receiver;
    private HashMap<String, String> usersListMap;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);

        try {
            ObjectInputStream userFile = new ObjectInputStream(new FileInputStream("userFile"));
            User user = (User) userFile.readObject();
            userFile.close();

            userName = user.getName();
            server = user.getIP();
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }

        receiver = new ReceiverClient(this);
        receiver.start();

        sender = new Sender();
        sender.sendConnection(server, userName);

        chat = "";
    }

    // ---------- Setter y Getter de userName ----------
    // ---------- Establece un valor a userName ----------
    public void setUserName(String userName) {
        this.userName = userName;
    }

    // ---------- Desvuelve el valor de userName ----------s
    public String getUserName() {
        return userName;
    }

    // ---------- Actualizar Lista de Usuarios Conectados ----------
    public void updateUsersList(HashMap<String, String> usersList) {
        usersListMap = usersList;
        DefaultListModel model = new DefaultListModel();
        for (String name : usersList.values()) {
            if (!this.userName.equals(name)) {
                model.addElement(name);
            }
        }
        this.usersList.setModel(model);

        if (this.usersList.getSelectedValue() == null || this.usersList.getSelectedValue() == "") {
            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, "selectedChat");
        }
    }

    public void setChatArea(String message) {
        chatArea.setText(message);
    }

    public String getChatArea() {
        return chatArea.getText();
    }

    public void close() {
        Login login = new Login();
        login.setErrorLabel("Server Cerrado");
        login.setVisible(true);
        receiver.finish();
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        mainPanel = new javax.swing.JPanel();
        selectedChat = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        chatPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LanChat - Home");
        setMinimumSize(new java.awt.Dimension(922, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jSplitPane1.setBackground(new java.awt.Color(25, 29, 38));
        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setDividerSize(3);
        jSplitPane1.setForeground(new java.awt.Color(25, 29, 38));
        jSplitPane1.setResizeWeight(0.2);

        mainPanel.setBackground(new java.awt.Color(19, 24, 30));
        mainPanel.setLayout(new java.awt.CardLayout());

        selectedChat.setOpaque(false);

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chaticon.png"))); // NOI18N

        javax.swing.GroupLayout selectedChatLayout = new javax.swing.GroupLayout(selectedChat);
        selectedChat.setLayout(selectedChatLayout);
        selectedChatLayout.setHorizontalGroup(
            selectedChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        selectedChatLayout.setVerticalGroup(
            selectedChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        mainPanel.add(selectedChat, "selectedChat");

        chatPanel.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(55, 58, 65));
        jPanel6.setForeground(new java.awt.Color(138, 142, 151));
        jPanel6.setPreferredSize(new java.awt.Dimension(706, 50));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Gonzalo González Oliveras");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setBorder(null);

        chatArea.setEditable(false);
        chatArea.setBackground(new java.awt.Color(19, 24, 30));
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chatArea.setForeground(new java.awt.Color(255, 255, 255));
        chatArea.setRows(5);
        chatArea.setBorder(null);
        jScrollPane3.setViewportView(chatArea);

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 50));

        jScrollPane2.setBorder(null);

        messageArea.setBackground(new java.awt.Color(55, 58, 65));
        messageArea.setColumns(1);
        messageArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageArea.setForeground(new java.awt.Color(148, 152, 161));
        messageArea.setLineWrap(true);
        messageArea.setRows(1);
        messageArea.setWrapStyleWord(true);
        messageArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        messageArea.setCaretColor(new java.awt.Color(12, 189, 55));
        messageArea.setSelectedTextColor(new java.awt.Color(19, 24, 30));
        messageArea.setSelectionColor(new java.awt.Color(12, 189, 55));
        jScrollPane2.setViewportView(messageArea);

        sendButton.setBackground(new java.awt.Color(55, 58, 65));
        sendButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sendicon.png"))); // NOI18N
        sendButton.setBorder(null);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout chatPanelLayout = new javax.swing.GroupLayout(chatPanel);
        chatPanel.setLayout(chatPanelLayout);
        chatPanelLayout.setHorizontalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        chatPanelLayout.setVerticalGroup(
            chatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chatPanelLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(chatPanel, "chatPanel");

        jSplitPane1.setRightComponent(mainPanel);

        jPanel2.setBackground(new java.awt.Color(25, 29, 38));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LanChat");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(138, 142, 151));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuarios Conectados");

        jSeparator1.setBackground(new java.awt.Color(25, 29, 38));
        jSeparator1.setForeground(new java.awt.Color(25, 29, 38));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 189, 55), 3, true));

        jScrollPane1.setBorder(null);

        usersList.setBackground(new java.awt.Color(25, 29, 38));
        usersList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usersList.setForeground(new java.awt.Color(138, 142, 151));
        usersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Marco del Uría", "Gastón Blasco Gonzalez", "Gonzalo González Oliveras", "Moisés Reig Pallarès", "Sarita Parra Palacios", "Gilberto de Solana", "Mohamed Manjón Amor", "Juan Bautista Amo-Gimenez", "Toni Pelayo", "Jennifer Font Juan", "Marco del Uría", "Gastón Blasco Gonzalez", "Gonzalo González Oliveras", "Moisés Reig Pallarès", "Sarita Parra Palacios", "Gilberto de Solana", "Mohamed Manjón Amor", "Juan Bautista Amo-Gimenez", "Toni Pelayo", "Jennifer Font Juan", "Marco del Uría", "Gastón Blasco Gonzalez", "Gonzalo González Oliveras", "Moisés Reig Pallarès", "Sarita Parra Palacios", "Gilberto de Solana", "Mohamed Manjón Amor", "Juan Bautista Amo-Gimenez", "Toni Pelayo", "Jennifer Font Juan" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        usersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersList.setToolTipText("");
        usersList.setFixedCellHeight(28);
        usersList.setSelectionBackground(new java.awt.Color(169, 230, 252));
        usersList.setSelectionForeground(new java.awt.Color(19, 24, 30));
        usersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String content = userName + ":\n" + messageArea.getText() + "\n\n";
        String toIp = "";
        for (String ip : usersListMap.keySet()) {
            if (usersListMap.get(ip).equals(usersList.getSelectedValue())) {
                toIp = ip;
            }
        }
        String toName = usersList.getSelectedValue();
        messageArea.setText("");

        sender.sendMessage(content, userName, toIp, toName, server);
        MessageSaves.Serialize(getChatArea() + content, userName, toName);
        setChatArea(MessageSaves.Deserialize(userName, toName));
    }//GEN-LAST:event_sendButtonActionPerformed

    private void usersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersListMouseClicked
        if (usersList.getSelectedValue() != null && !usersList.getSelectedValue().equals(chat)) {
            chat = usersList.getSelectedValue();

            CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
            cardLayout.show(mainPanel, "chatPanel");

            setChatArea(MessageSaves.Deserialize(userName, usersList.getSelectedValue()));
            nameLabel.setText(usersList.getSelectedValue());
            messageArea.setText("");
        }
    }//GEN-LAST:event_usersListMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        sender.sendDisconnection(server);
        receiver.finish();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatArea;
    private javax.swing.JPanel chatPanel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel selectedChat;
    private javax.swing.JButton sendButton;
    private javax.swing.JList<String> usersList;
    // End of variables declaration//GEN-END:variables
}
